# 1.1 Crie vetor de 1D com os números de 0 a 9:

In [23]:
my_array =[0,1,2,3,4,5,6,8,9]
print(f"O array é {my_array}")

O array é [0, 1, 2, 3, 4, 5, 6, 8, 9]


# 1.2 Crie uma matriz 3x3 preenchida com zeros:

In [24]:
import numpy as np
my_array_3x3 = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(f"{my_array_3x3}")

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 1.3 Crie uma matriz identidade 4x4:

In [25]:
import numpy as np
identidade = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(f"{identidade}")

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 1.4 Crie um array 2x2 preenchido com o valor 7:


In [26]:
import numpy as np
matris2x2 = np.array([[7,7],[7,7]])
print(f"{matris2x2}")

[[7 7]
 [7 7]]


# 1.5 Crie um vetor com 10 valores igualmente espaçados entre 0 e 1:


In [27]:
import numpy as np
vecto = np.linspace(0,1,10)
print(f"{vecto}")


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 2.1 Dados os vetores a = [1, 2, 3] e b = [4, 5, 6], calcule:
# - A soma de a e b;
# - A multiplicação elemento a elemento (a * b);
# - O produto escalar de a e b.


In [28]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

soma = a + b
multiplicacao = a * b
escalar = 0 
for i in range(3):
    produto = a[i] * b[i]
    escalar += produto
print(f"{soma},{multiplicacao} ,{escalar}")

[5 7 9],[ 4 10 18] ,32
