Link para o github da materia onde esta os notebooks: https://github.com/Alomyr/Apredizado-de-maquina-supervisonado.git

todos os notebooks foram escritos e testados no vscode usando as extensoes: colab e jupyter

# 1.1 Crie vetor de 1D com os números de 0 a 9:

In [1]:
import numpy as np
my_array = np.array([0,1,2,3,4,5,6,8,9])
print(f"{my_array}")

[0 1 2 3 4 5 6 8 9]


# 1.2 Crie uma matriz 3x3 preenchida com zeros:

In [2]:
from turtle import shape

import numpy as np
my_array_3x3 = np.zeros(shape=(3,3))
print(f"{my_array_3x3}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 1.3 Crie uma matriz identidade 4x4:

In [3]:
import numpy as np
identidade = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
print(f"{identidade}")

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 1.4 Crie um array 2x2 preenchido com o valor 7:


In [4]:
import numpy as np
matris2x2 = np.array([[7,7],[7,7]])
print(f"{matris2x2}")

[[7 7]
 [7 7]]


# 1.5 Crie um vetor com 10 valores igualmente espaçados entre 0 e 1:


In [5]:
import numpy as np
vecto = np.linspace(0,1,10)
print(f"{vecto}")


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 2.1 Dados os vetores a = [1, 2, 3] e b = [4, 5, 6], calcule:
# - A soma de a e b;
# - A multiplicação elemento a elemento (a * b);
# - O produto escalar de a e b.


In [6]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

soma = a + b
multiplicacao = a * b
escalar = 0 
for i in range(3):
    produto = a[i] * b[i]
    escalar += produto
print(f"{soma},{multiplicacao} ,{escalar}")

[5 7 9],[ 4 10 18] ,32


# 2.2 Calcule a norma (magnitude) do vetor v = [3, 4]:


In [7]:
import numpy as np
from math import sqrt
vector = np.array([3,4])
soma = 0
for i in range(len(vector)):
    produto = vector[i] ** 2
    soma += produto
magnitude = print(sqrt((soma) ))

5.0


# 2.3 Crie um vetor c com valores de 1 a 5 e inverta a ordem dos elementos:

In [8]:
import numpy as np
vector = np.array([1,2,3,4,5])
print(f"vector normal {vector}\nvector invertido = ", end=" ")

for i in reversed(vector):
    print(i, end=" ")

vector normal [1 2 3 4 5]
vector invertido =  5 4 3 2 1 

# 3.1 Dadas as matrizes A = [[1, 2], [3, 4]] e B = [[5, 6], [7, 8]], calcule:
# - Soma;
# - Produto interno (escalar);
# - Transposta de A.

In [9]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
soma = a + b
escalar = 0 

for i in range(len(a+b)):
    for j in range (len(a+b)):
        produto = a[i][j] * b[i][j]
        escalar += produto
print(f"a soma das matrizes:\n {soma} \n, o produto escalar: {escalar}\n")

transpostaA=a.T
print(transpostaA)

a soma das matrizes:
 [[ 6  8]
 [10 12]] 
, o produto escalar: 70

[[1 3]
 [2 4]]


# 3.2 Crie uma matriz 2x3 de distribuição normal com média 0.5 e desvio padrão 0.2:

In [10]:
import numpy as np
matriz = np.random.normal(0.5,0.2,(2,3))
for i in range(len(matriz)):
    print(matriz[i])

[0.531466   0.77786067 0.50057031]
[0.46242211 0.53429382 0.50732717]


# 4.1 Dado o vetor x = [10, 20, 30, 40, 50]:
# - Acesse o terceiro elemento;
# - Extraia os elementos do segundo ao quarto.



In [11]:
x = [10,20,30,40,50]
print(x)
print(x[2])
i = int(1)
print(x[1:4])

[10, 20, 30, 40, 50]
30
[20, 30, 40]


# 4.2 Dada a matriz D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]:
# - Acesse o elemento na segunda linha e terceira coluna.
# - Extraia a submatriz das duas primeiras linhas e colunas.

In [12]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
print(matriz[1,2])
print(matriz[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2]
 [4 5]]


# 5.1 Dado o vetor y = [1, 5, 3, 8, 2], calcule:
# - A média, mediana e desvio padrão;
# - O valor máximo e mínimo.

In [13]:
import numpy as np
y = np.array([1,5,3,8,2])

media =  np.mean(y)
print(f"{media}")
mediana = np.median(y)
print(f"{mediana}")
desvio_padrao = np.std(y)
print(f"{desvio_padrao}")
minimo = y.min()
print(minimo)
maximo = y.max()
print(f"{maximo}")

3.8
3.0
2.481934729198171
1
8


# 5.2 Calcule o valor máximo das colunas da matriz E = [[1, 5], [3, 2]]:


In [14]:
import numpy as np
E = np.array([[1,5],[3,2]])
maximo = E.max(axis=0)
print(f"{maximo}")

[3 5]


# 6.1 Transforme o vetor [1, 2, 3, 4, 5, 6] em uma matriz 2x3:

In [15]:
import numpy as np
vetor = np.array([1,2,3,4,5,6])
matriz = vetor.reshape(2,3 )
print(f"{matriz}")

[[1 2 3]
 [4 5 6]]


# 6.2 Concatene verticalmente as matrizes F = [[1, 2]] e G = [[3, 4]]:

In [16]:
import numpy as np
F = np.array([[1,2]])
G = np.array([[3,4]])
matriz = np.concatenate((F,G), axis=0)
print(f"{matriz}")

[[1 2]
 [3 4]]
